first try on upgrading to cake 4
elstc/cakephp-activity-logger pull request #14
Opened 2020-08-28 12:53 UTC by gringlas

Hi everybody, 
I have created an upgrade of this plugin for cake 4.0.* . The phpunit testsuite went through without any errors and I've tested the version on one of my projects. 
This is my first pull request ever, so please bear that in mind, in case I have done anything wrong. Would be great to update this fine plugin though to use it in cake4. 

Thank you and greetings from Germany,
 Sebastian Köller

2020-09-04 05:45 UTC, nojimage commented
Thank you for your great work.

I hasn't been fully reviewed it yet, but it seems that some unnecessary files have been committed.

- .idaa/
- .phpunit.result.cache
- composer.lock
- main

Can you exclude these files from the PR?

2020-09-04 06:31 UTC, gringlas commented
Thats good to hear :) 
I've removed alle unnecessary files, but I think the composer.lock needs to stay in version control, like stated here:
https://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control
Or am I wrong in that point?

2020-09-04 11:36 UTC, nojimage commented
[https://getcomposer.org/doc/02-libraries.md#lock-file](https://getcomposer.org/doc/02-libraries.md#lock-file)
> For your library you may commit the composer.lock file if you want to. This can help your team to always test against the same dependency versions. However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.

It is better not to include composer.lock because the library needs to work in various environments.
It also gets in the way when testing with different PHP/CakePHP versions.

(If your application runs in a single environment, I recommend including composer.lock.

2020-09-07 05:50 UTC, gringlas commented
Ok, thanks for the explaination. I've removed composer.lock and added also added it to .gitignore.

2020-09-08 03:03 UTC, nojimage requested changes
Please change the following points if possible. thanks.

2020-09-08 03:03 UTC, nojimage commented on composer.json
> +        "cakephp/cakephp": "4.0.*"
Please change to like bellow, include CakePHP 4.1.

```suggestion
        "cakephp/cakephp": "^4.0"
```

2020-09-08 05:39 UTC, gringlas commented on src/Model/Behavior/LoggerBehavior.php
> +            $logTable->save($log);
Nope. Can't remember why I did that, but I reverted that change and tests are passing.

2020-09-08 05:40 UTC, gringlas commented on tests/Fixture/ActivityLogsFixture.php
> -        'id' => ['type' => 'biginteger', 'length' => 20, 'unsigned' => true, 'null' => false, 'default' => null, 'comment' => '', 'autoIncrement' => true, 'precision' => null],
I'm not exactly sure, but are you refering to the change of type biginteger to integer? I've reverted that change and tests are passing.

2020-09-08 05:46 UTC, gringlas commented
I have commited a version with your changes and also removed syntaxCheck atrribute in phpunity.xml.dist as it was removed long ago (https://stackoverflow.com/questions/44328114/phpunit-what-does-syntaxcheck-configuration-parameter-stands-for-exactly)

2020-09-08 07:31 UTC, nojimage commented
Thank you for fixes. I'll merge this.

2020-09-08 07:39 UTC, merged